console.log("Preparar un batido de banana en 5 pasos:")
console.log("1-Coloca 1 o 2 plátanos en rodajas en la licuadora")
console.log("2-Añade 1/2 taza de leche")
console.log("3-Añade una taza de hielo")
console.log("4-Licua los ingredientes hasta obtener una mezcla homogénea.")
console.log("5-Agrega azucar a gusto")
